### PR TITLE
add GA config

### PR DESCRIPTION
**Pull request by davebuckleyCDEI**

### CODE REVIEW

**Comment by tcbegley** [comment]
If you're adding Google analytics, it's worth double checking the GDPR implications + whether you are required to ask for cookie consent etc.

**Comment by davebuckleyCDEI** [comment]
Hi @tcbegley, I've made a change to add a consent popup - we're discussing internally on the wording to use and how to configure GA.

When running locally, I've not been able to get any data to actually appear in GA (with any GA plugin), though with debug enabled the console log suggests it's doing the right thing. Probably there is something not quite configured right on my side.

**Comment by tcbegley** [comment]
Sounds good. I figured CDEI is under particular scrutiny when it comes to these sorts of things.

On the second point, in my experience analytics services like Google can generally tell when the site is running locally and don't count those visits towards the analytics. If you're not getting obvious errors the easiest thing might be to simply deploy and see what happens (since reverting it is easy enough).

**Comment by davebuckleyCDEI** [comment]
Thanks Tom. Got it to send some data by tweaking some cookie properties to account for running on localhost, but should work as is when deployed proper.

**Review by ahardingCDEI — APPROVED** [review]
Looks good to me.

**Pull request merged**
